-- 0001_init.sql — Competitive Intelligence schema (Phase 1: read path + catalog)
--
-- Plain PostgreSQL port of dashboard/backend/prisma/schema.prisma, targeting Neon
-- (interim) and the team's Postgres (later). Portability rule: standard SQL only —
-- no Neon-specific features — so `pg_dump | psql` migrates clean. See db/README.md.
--
-- The Prisma SQLite model JSON-encoded string[] into TEXT columns; here those become
-- native JSONB. @updatedAt is replaced by the set_updated_at() trigger below.
--
-- Apply:  psql "$DATABASE_URL" -f db/migrations/0001_init.sql

BEGIN;

-- ── Migration bookkeeping ────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS schema_migrations (
  version    text PRIMARY KEY,
  applied_at timestamptz NOT NULL DEFAULT now()
);

-- ── Shared updated_at trigger (replaces Prisma @updatedAt) ───────────────────
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- ── competitors ──────────────────────────────────────────────────────────────
CREATE TABLE competitors (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name               text NOT NULL UNIQUE,
  -- JSON arrays of strings (sitemaps, include/exclude path patterns, ignored hosts)
  sitemap_urls       jsonb NOT NULL DEFAULT '[]'::jsonb,
  include_patterns   jsonb NOT NULL DEFAULT '[]'::jsonb,
  exclude_patterns   jsonb NOT NULL DEFAULT '[]'::jsonb,
  -- subdomain hostnames to skip; a URL is dropped if its host equals or is a
  -- subdomain of any entry (e.g. "community.elevenlabs.io")
  ignored_subdomains jsonb NOT NULL DEFAULT '[]'::jsonb,
  use_snapshot_diff  boolean NOT NULL DEFAULT false,
  active             boolean NOT NULL DEFAULT true,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);
CREATE TRIGGER trg_competitors_updated_at BEFORE UPDATE ON competitors
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ── runs ─────────────────────────────────────────────────────────────────────
CREATE TABLE runs (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  started_at    timestamptz NOT NULL DEFAULT now(),
  finished_at   timestamptz,
  hours_window  integer NOT NULL,
  status        text NOT NULL DEFAULT 'running'
                  CHECK (status IN ('success','partial','failed','running')),
  -- "trigger" is a SQL keyword — quoted to preserve the column name
  "trigger"     text NOT NULL DEFAULT 'scheduled'
                  CHECK ("trigger" IN ('scheduled','manual')),
  digest_text   text,
  slack_status  text,
  email_status  text,
  error_summary text,
  created_at    timestamptz NOT NULL DEFAULT now()
);

-- ── run_competitors (per-run, per-competitor result) ─────────────────────────
CREATE TABLE run_competitors (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_id             bigint NOT NULL REFERENCES runs(id)        ON DELETE CASCADE,
  competitor_id      bigint NOT NULL REFERENCES competitors(id) ON DELETE CASCADE,
  total_sitemap_urls integer NOT NULL DEFAULT 0,
  new_page_count     integer NOT NULL DEFAULT 0,
  relevant_count     integer NOT NULL DEFAULT 0,
  checked_at         timestamptz,
  -- 'partial' = some pages failed to scrape but the run completed (matches ingest)
  status             text NOT NULL DEFAULT 'success'
                       CHECK (status IN ('success','partial','failed')),
  error              text,
  UNIQUE (run_id, competitor_id)
);
CREATE INDEX idx_run_competitors_competitor ON run_competitors (competitor_id);

-- ── pages (one archive item per detected URL, deduped by competitor+url) ─────
CREATE TABLE pages (
  id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  run_competitor_id bigint NOT NULL REFERENCES run_competitors(id) ON DELETE CASCADE,
  competitor_id     bigint NOT NULL REFERENCES competitors(id)     ON DELETE CASCADE,
  url               text NOT NULL,
  lastmod           timestamptz,
  detection_source  text CHECK (detection_source IN ('snapshot_diff','lastmod')),
  title             text,
  description       text,
  text_preview      text,
  text_length       integer,
  first_seen_run_id bigint REFERENCES runs(id) ON DELETE SET NULL,
  scraped_at        timestamptz,
  created_at        timestamptz NOT NULL DEFAULT now(),
  UNIQUE (competitor_id, url)
);
CREATE INDEX idx_pages_scraped_at        ON pages (scraped_at);
CREATE INDEX idx_pages_competitor        ON pages (competitor_id);
CREATE INDEX idx_pages_run_competitor    ON pages (run_competitor_id);

-- ── classifications (0–1 per page; the rubric output) ────────────────────────
CREATE TABLE classifications (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id         bigint NOT NULL UNIQUE REFERENCES pages(id) ON DELETE CASCADE,
  relevant        boolean NOT NULL DEFAULT false,
  -- 0–100 confidence that the page reports a new product / new feature
  relevance_score integer CHECK (relevance_score BETWEEN 0 AND 100),
  signal_type     text CHECK (signal_type IN
                    ('new_product','new_feature','update','tangential','irrelevant')),
  product         text,
  -- category taxonomy is intentionally free text (13-cat → 6-tag reconciliation pending)
  category        text,
  summary         text,
  reasoning       text,
  model           text,
  rubric_version  text,
  classified_at   timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_classifications_category  ON classifications (category);
CREATE INDEX idx_classifications_relevant  ON classifications (relevant);

-- ── products (per-competitor catalog; makes product/category a lookup) ───────
CREATE TABLE products (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  competitor_id      bigint NOT NULL REFERENCES competitors(id) ON DELETE CASCADE,
  name               text NOT NULL,
  category           text,
  aliases            jsonb NOT NULL DEFAULT '[]'::jsonb,
  status             text NOT NULL DEFAULT 'active'
                       CHECK (status IN ('active','candidate','deprecated')),
  first_seen_page_id bigint REFERENCES pages(id) ON DELETE SET NULL,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now(),
  UNIQUE (competitor_id, name)
);
CREATE INDEX idx_products_status ON products (status);
CREATE TRIGGER trg_products_updated_at BEFORE UPDATE ON products
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ── telnyx_offerings (Telnyx side of the Competitors-tab map) ────────────────
CREATE TABLE telnyx_offerings (
  id          bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        text NOT NULL UNIQUE,
  category    text,
  description text,
  created_at  timestamptz NOT NULL DEFAULT now()
);

-- ── offering_comparisons (competitor product ↔ Telnyx offering verdict) ──────
CREATE TABLE offering_comparisons (
  id                 bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  competitor_id      bigint NOT NULL REFERENCES competitors(id) ON DELETE CASCADE,
  focus_area         text,
  competitor_product text,
  telnyx_offering_id bigint REFERENCES telnyx_offerings(id) ON DELETE SET NULL,
  verdict            text NOT NULL DEFAULT 'none'
                       CHECK (verdict IN
                         ('parity','gap','telnyx_ahead','competitor_ahead','none')),
  rationale          text,
  source             text NOT NULL DEFAULT 'manual'
                       CHECK (source IN ('inference','manual')),
  edited_by          text,
  created_at         timestamptz NOT NULL DEFAULT now(),
  updated_at         timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_offering_comparisons_competitor ON offering_comparisons (competitor_id);
CREATE INDEX idx_offering_comparisons_offering   ON offering_comparisons (telnyx_offering_id);
CREATE TRIGGER trg_offering_comparisons_updated_at BEFORE UPDATE ON offering_comparisons
  FOR EACH ROW EXECUTE FUNCTION set_updated_at();

-- ── snapshots (URL set per competitor; the snapshot-diff detection state) ────
CREATE TABLE snapshots (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  competitor_id bigint NOT NULL REFERENCES competitors(id) ON DELETE CASCADE,
  urls          jsonb NOT NULL DEFAULT '[]'::jsonb,
  url_count     integer NOT NULL,
  saved_at      timestamptz NOT NULL DEFAULT now()
);
-- latest-snapshot lookup for the diff
CREATE INDEX idx_snapshots_competitor_saved ON snapshots (competitor_id, saved_at DESC);

INSERT INTO schema_migrations (version) VALUES ('0001_init') ON CONFLICT DO NOTHING;

COMMIT;
