-- 0002_write_features.sql — Phase 2: operator write surfaces (Training + Sources)
--
-- feedback, guidance, and removal_requests. These power the Training queue and the
-- approval-gated endpoint/subdomain removals. Separated from 0001 so the read path
-- can ship first; this migration is applied when the write features land.
--
-- Apply:  psql "$DATABASE_URL" -f db/migrations/0002_write_features.sql

BEGIN;

-- ── feedback (operator action on a page's classification) ────────────────────
CREATE TABLE feedback (
  id              bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  page_id         bigint NOT NULL REFERENCES pages(id)        ON DELETE CASCADE,
  competitor_id   bigint NOT NULL REFERENCES competitors(id)  ON DELETE CASCADE,
  action          text NOT NULL
                    CHECK (action IN
                      ('confirm','flag_irrelevant','recategorize','reassign_product')),
  reason_category text CHECK (reason_category IN
                    ('marketing','customer_story','careers_or_legal','wrong_subdomain',
                     'duplicate','wrong_product','wrong_category','not_a_release','other')),
  reason          text,
  operator        text,
  created_at      timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_feedback_page       ON feedback (page_id);
CREATE INDEX idx_feedback_competitor ON feedback (competitor_id);

-- ── guidance (free-text prompt guidance; competitor_id NULL = global) ────────
CREATE TABLE guidance (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  competitor_id bigint REFERENCES competitors(id) ON DELETE CASCADE,
  "text"        text NOT NULL,
  active        boolean NOT NULL DEFAULT true,
  operator      text,
  created_at    timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX idx_guidance_competitor ON guidance (competitor_id);
CREATE INDEX idx_guidance_active     ON guidance (active);

-- ── removal_requests (approval-gated drop-from-consideration) ────────────────
-- kind=endpoint → competitor.exclude_patterns; kind=subdomain → ignored_subdomains
CREATE TABLE removal_requests (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  competitor_id bigint NOT NULL REFERENCES competitors(id) ON DELETE CASCADE,
  kind          text NOT NULL DEFAULT 'endpoint'
                  CHECK (kind IN ('endpoint','subdomain')),
  -- value = path/pattern (endpoint) ; host = hostname (subdomain)
  value         text,
  host          text,
  status        text NOT NULL DEFAULT 'pending'
                  CHECK (status IN ('pending','approved','rejected')),
  requested_by  text,
  resolved_by   text,
  page_id       bigint REFERENCES pages(id) ON DELETE SET NULL,
  created_at    timestamptz NOT NULL DEFAULT now(),
  resolved_at   timestamptz
);
CREATE INDEX idx_removal_requests_status     ON removal_requests (status);
CREATE INDEX idx_removal_requests_competitor ON removal_requests (competitor_id);

INSERT INTO schema_migrations (version) VALUES ('0002_write_features') ON CONFLICT DO NOTHING;

COMMIT;
